### ISSUE TITLE
ver 9.4.0 not compatible with path-to-regexp ?

### ISSUE THREAD

**Issue by maxyou** [koajs/router#104]
I set up a very base project with koa+typescript+router.

if
```
  "dependencies": {
    "koa": "2.13.0",
    "koa-router": "^9.4.0"
  },
```
then
`PS D:\Dev\TypeScript\koa-typescript-starter-master> npm run watch-server

> koa-typescript-starter@1.0.0 watch-server D:\Dev\TypeScript\koa-typescript-starter-master
> nodemon --watch 'src/**/*' -e ts,tsx --exec ts-node ./src/server.ts

[nodemon] 2.0.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): 'src\**\*'
[nodemon] watching extensions: ts,tsx
[nodemon] starting `ts-node ./src/server.ts`

D:\Dev\TypeScript\koa-typescript-starter-master\node_modules\path-to-regexp\src\index.ts:157
    throw new TypeError(`Unexpected ${nextType} at ${index}, expected ${type}`);
          ^
TypeError: Unexpected MODIFIER at 1, expected END
    at mustConsume (D:\Dev\TypeScript\koa-typescript-starter-master\node_modules\path-to-regexp\src\index.ts:157:11)
    at parse (D:\Dev\TypeScript\koa-typescript-starter-master\node_modules\path-to-regexp\src\index.ts:228:5)
    at stringToRegexp (D:\Dev\TypeScript\koa-typescript-starter-master\node_modules\path-to-regexp\src\index.ts:494:25)
    at pathToRegexp (D:\Dev\TypeScript\koa-typescript-starter-master\node_modules\path-to-regexp\src\index.ts:616:10)
    at new Layer (D:\Dev\TypeScript\koa-typescript-starter-master\node_modules\koa-router\lib\layer.js:43:17)
    at Router.register (D:\Dev\TypeScript\koa-typescript-starter-master\node_modules\koa-router\lib\router.js:570:17)
    at Router.(anonymous function) [as get] (D:\Dev\TypeScript\koa-typescript-starter-master\node_modules\koa-router\lib\router.js:200:12) 
    at Object.<anonymous> (D:\Dev\TypeScript\koa-typescript-starter-master\src\server.ts:22:8)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module.m._compile (D:\Dev\TypeScript\koa-typescript-starter-master\node_modules\ts-node\src\index.ts:1043:23)
[nodemon] app crashed - waiting for file changes before starting...
`

if
`  "dependencies": {
    "koa": "2.13.0",
    "koa-router": "7.4.0"
  },`

it runs OK! 
ver 7 is no problem

**Comment by anthony-kenikh** [comment]
@maxyou Could you provide your code?
Most likely the problem is what is you should change usage of `*` in routes to `(.*)` or `:splat*` as per [koajs/router v9 changelog](https://github.com/koajs/router/blob/master/history.md).

**Comment by maxyou** [comment]
> @maxyou Could you provide your code?
> Most likely the problem is what is you should change usage of `*` in routes to `(.*)` or `:splat*` as per [koajs/router v9 changelog](https://github.com/koajs/router/blob/master/history.md).

Yes! You are right! this issue is from:

`router.get('/*', async (ctx) => {
    ctx.body = 'Hello World!';
});`

After I remove '*', everything is OK!
